dist: xenial
language: python
cache: pip
python:
  - 3.6
  - 3.7
  - 3.8
env:
  - DJANGO=2.2
  - DJANGO=3.0
jobs:
  fast_finish: true
install: pip install tox-travis codecov
script: tox
after_success:
  - codecov